#!/bin/sh
# find out which card number the DINAH got loaded with.
card=`/usr/bin/readlink /dev/snd/DINAH | sed -e 's/^.*\(.\)$/\1/'`
if [ -z "$card" ]; then
   echo unable to find /dev/snd/DINAH >&2
   exit 1
fi
# edit the soundmodem.conf to fix the device reference for the given card.
echo DINAH is soundmodem card $card
sed -i.bak -e "s/device=\"plughw.*\" /device=\"plughw:${card},0\" /" /etc/ax25/soundmodem.conf
exec /usr/sbin/soundmodem --daemonize -s
